[target.x86_64-unknown-linux-musl]
linker = "x86_64-unknown-linux-musl-gcc"

[env]
CC_x86_64_unknown_linux_musl = "x86_64-unknown-linux-musl-gcc"
CXX_x86_64_unknown_linux_musl = "x86_64-unknown-linux-musl-g++"
AR_x86_64_unknown_linux_musl = "x86_64-unknown-linux-musl-ar"
